In [1]:
#loading libraries:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv(r"C:\Users\Anushkha Bhagra\Downloads\ML\classification\Churn_Modelling.xls")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# drop the useless columns:
df.drop(columns=["RowNumber","CustomerId","Surname"],inplace=True)

In [4]:
#handling categorical data:
label = LabelEncoder()
df["encoded_geo"] = label.fit_transform(df["Geography"])
var1 = dict(zip(df["Geography"],df["encoded_geo"]))
print(var1)

df["encoded_gender"] = label.fit_transform(df["Gender"])
var2 = dict(zip(df["Gender"],df["encoded_gender"]))
print(var2)

{'France': 0, 'Spain': 2, 'Germany': 1}
{'Female': 0, 'Male': 1}

In [5]:
#dropping columns:
df.drop(columns=["Geography", "Gender"],inplace=True)

In [6]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,encoded_geo,encoded_gender
0,619,42,2,0.00,1,1,1,101348.88,1,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,2,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,2,0

In [9]:
#featuring:
x = df.drop(columns=["Exited"])
y = df["Exited"]

In [10]:
#data splittinf:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [14]:
scalar = StandardScaler()
x_train_scaler = scalar.fit_transform(x_train)
x_test_scaler = scalar.transform(x_test)

In [17]:
# model selection:
logistic = LogisticRegression(max_iter= 10000)

knn = KNeighborsClassifier(n_neighbors=5)

In [18]:
#model training using logistic regression:
logistic.fit(x_train_scaler,y_train)

LogisticRegression(max_iter=10000)

In [19]:
#model testing:
y_pred = logistic.predict(x_test_scaler)
accuracy_score(y_test,y_pred)

0.8155

In [20]:
#accuracy on train data:
y_pred_train = logistic.predict(x_train_scaler)
accuracy_score(y_train,y_pred_train)

0.807125

In [21]:
# model training using knn:
knn.fit(x_train_scaler,y_train)

KNeighborsClassifier()

In [22]:
#model testing:
y_pred = knn.predict(x_test_scaler)
accuracy_score(y_test,y_pred)

0.8355

In [23]:
#accuracy on train data:
y_pred_train = knn.predict(x_train_scaler)
accuracy_score(y_train,y_pred_train)

0.877875

In [27]:
# predictive model using knn:
# CreditScore	Age	Tenure	Balance	NumOfProducts	HasCrCard	IsActiveMember	EstimatedSalary		encoded_geo	encoded_gender
credict_score = int(input("enter the value"))
age = int(input("enter the age"))
tenure = int(input("enter the tenure"))
balance = float(input("enter your balance"))
products = int(input("enter the no of products"))
cards = int(input("enter the credit cards you have press 1 or press 0"))
members = int(input("enter 1 if you ara active member press 0 if no"))
salary = int(input("enter your salary"))
geography = int(input("enter the geography-->{'France': 0, 'Spain': 2, 'Germany': 1}"))
gender = int(input("enter the gender-->{'Female': 0, 'Male': 1}"))

data = scalar.transform([[credict_score, age, tenure, balance,products,cards, members, salary,geography, gender]])
prediction = knn.predict(data)
if prediction ==0:
    print("not Exited")
else:
    print("Exited")

enter the value 600
enter the age 25
enter the tenure 4
enter your balance 45000.9
enter the no of products 3
enter the credit cards you have press 1 or press 0 1
enter 1 if you ara active member press 0 if no 1
enter your salary 5690900
enter the geography-->{'France': 0, 'Spain': 2, 'Germany': 1} 1
enter the gender-->{'Female': 0, 'Male': 1} 0

not Exited

E:\anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(