In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

In [19]:
df= pd.read_csv(r"C:\Users\Anushkha Bhagra\Downloads\ML\cardekho.csv")

In [20]:
df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,seats
0,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,5.0
1,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,5.0
2,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,5.0
3,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,5.0
4,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,5.0

In [21]:
df.isnull().sum()

year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
seats            221
dtype: int64

In [22]:
#filling the null values
df["mileage"] = df["mileage"].fillna(df["mileage"].mean())
df["engine"] = df["engine"].fillna(df["engine"].mean())
df["seats"] = df["seats"].fillna(df["seats"].mean())

In [23]:
#dropping the duplicates:
df.drop_duplicates(inplace=True)

In [24]:
df["fuel"].value_counts()

fuel
Diesel    3747
Petrol    3065
CNG         56
LPG         38
Name: count, dtype: int64

In [25]:
df.seller_type.value_counts()

seller_type
Individual          6198
Dealer               681
Trustmark Dealer      27
Name: count, dtype: int64

In [26]:
df.transmission.value_counts()

transmission
Manual       6322
Automatic     584
Name: count, dtype: int64

In [27]:
df.owner.value_counts()

owner
First Owner             4225
Second Owner            1971
Third Owner              536
Fourth & Above Owner     169
Test Drive Car             5
Name: count, dtype: int64

In [28]:
#handling categorical data:
df["fuel"] = df["fuel"].map({"Diesel":0,"Petrol":1,"CNG":2,"LPG":3})
df["seller_type"] = df["seller_type"].map({"Individual":0,"Dealer":1,"Trustmark Dealer":2})
df["transmission"] = df["transmission"].map({"Manual":0,"Automatic":1})
df["owner"] = df["owner"].map({"First Owner":0,"Second Owner":1,"Third Owner":2,"Fourth & Above Owner":3,"Test Drive Car":4})

In [29]:
df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,seats
0,2014,450000,145500,0,0,0,0,23.40,1248.0,5.0
1,2014,370000,120000,0,0,0,1,21.14,1498.0,5.0
2,2006,158000,140000,1,0,0,2,17.70,1497.0,5.0
3,2010,225000,127000,0,0,0,0,23.00,1396.0,5.0
4,2007,130000,120000,1,0,0,0,16.10,1298.0,5.0

In [31]:
#feature selection:
x = df.drop(columns=["selling_price"])
y = df["selling_price"]

In [32]:
#data splitting:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [37]:
#data scaling: only of the input data means only x_train and x_test
scalar = StandardScaler()
x_train_scale = scalar.fit_transform(x_train)
x_test_scale = scalar.fit_transform(x_test)

In [39]:
#model selection:
model = LinearRegression()

#model training:
model.fit(x_train_scale,y_train)

LinearRegression()

In [40]:
#accuracy:
y_pred = model.predict(x_test_scale)
r2_score(y_test,y_pred)

0.5019471192707244