In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeRegressor # decision tree
from sklearn.ensemble import RandomForestRegressor # random forest

In [13]:
df = pd.read_csv(r"C:\Users\Anushkha Bhagra\Downloads\ML\cardekho.csv")

In [14]:
df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,seats
0,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,5.0
1,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,5.0
2,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,5.0
3,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,5.0
4,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,5.0

In [15]:
#preprocessing of data:
df.isnull().sum()

year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
seats            221
dtype: int64

In [16]:
df["mileage"] = df["mileage"].fillna(df["mileage"].mean())
df["engine"] = df["engine"].fillna(df["engine"].mean())
df["seats"] = df["seats"].fillna(df["seats"].mean())

In [17]:
df.drop_duplicates(inplace=True)

In [19]:
# encoding of categorical data:
label = LabelEncoder()
df["encoded_fuel"] = label.fit_transform(df["fuel"])
var1 = dict(zip(df["fuel"],df["encoded_fuel"]))
print(var1)

df["encoded_seller"] = label.fit_transform(df["seller_type"])
var2 = dict(zip(df["seller_type"],df["encoded_seller"]))
print(var2)

df["encoded_trans"] = label.fit_transform(df["transmission"])
var3 = dict(zip(df["transmission"],df["encoded_trans"]))
print(var3)

df["encoded_owner"] = label.fit_transform(df["owner"])
var4 = dict(zip(df["owner"],df["encoded_owner"]))
print(var4)

{'Diesel': 1, 'Petrol': 3, 'LPG': 2, 'CNG': 0}
{'Individual': 1, 'Dealer': 0, 'Trustmark Dealer': 2}
{'Manual': 1, 'Automatic': 0}
{'First Owner': 0, 'Second Owner': 2, 'Third Owner': 4, 'Fourth & Above Owner': 1, 'Test Drive Car': 3}

In [20]:
#dropping the duplicate columns:
df.drop(columns=["fuel","seller_type","transmission","owner"],inplace=True)

In [21]:
df.head()

,year,selling_price,km_driven,mileage,engine,seats,encoded_fuel,encoded_seller,encoded_trans,encoded_owner
0,2014,450000,145500,23.40,1248.0,5.0,1,1,1,0
1,2014,370000,120000,21.14,1498.0,5.0,1,1,1,2
2,2006,158000,140000,17.70,1497.0,5.0,3,1,1,4
3,2010,225000,127000,23.00,1396.0,5.0,1,1,1,0
4,2007,130000,120000,16.10,1298.0,5.0,3,1,1,0

In [22]:
#feature selection :
x = df.drop(columns=["selling_price"])
y = df["selling_price"]

In [23]:
#data splitting:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [48]:
#scaling:
#scalar = StandardScaler()
#x_train_scalar = scalar.fit_transform(x_train)
#x_test_scalar = scalar.fit_transform(x_test)

In [37]:
#model selection:
tree = DecisionTreeRegressor(max_depth=7,random_state=42)
random = RandomForestRegressor(n_estimators=100,max_depth= 5, random_state=42)

In [46]:
#model training using rndom tree
tree.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=7, random_state=42)

In [47]:
#accuracy on test data:
y_pred = tree.predict(x_test)
r2_score(y_test,y_pred)

0.8085090477594502

In [42]:
#model training using random forest:
random.fit(x_train,y_train)

RandomForestRegressor(max_depth=5, random_state=42)

In [43]:
#model accuracy:
#accuracy on test data:
y_pred = random.predict(x_test)
r2_score(y_test,y_pred)

0.756394988391123