In [22]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv(r"C:\Users\Anushkha Bhagra\Downloads\ML\House_price_dataset.csv")
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [3]:
#preprocessing of the data:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
label = LabelEncoder()
df["encoded_street"] = label.fit_transform(df["street"])
var1 = dict(zip(df["street"],df["encoded_street"]))
print(var1)

df["encoded_city"] = label.fit_transform(df["city"])
var2 = dict(zip(df["city"],df["encoded_city"]))
print(var2)

df["encoded_zip"] = label.fit_transform(df["statezip"])
var3 = dict(zip(df["statezip"],df["encoded_zip"]))
print(var3)

df["encoded_country"] = label.fit_transform(df["country"])
var4 = dict(zip(df["country"],df["encoded_country"]))
print(var4)

{'18810 Densmore Ave N': 1522, '709 W Blaine St': 3899, '26206-26214 143rd Ave SE': 2291, '857 170th Pl NE': 4263, '9105 170th Ave NE': 4352, '522 NE 88th St': 3521, '2616 174th Ave NE': 2286, '23762 SE 253rd Pl': 2038, '46611-46625 SE 129th St': 3369, '6811 55th Ave NE': 3846, 'Burke-Gilman Trail': 4510, '3838-4098 44th Ave NE': 3025, '1833 220th Pl NE': 1473, '2504 SW Portland Ct': 2176, '3534 46th Ave NE': 2905, '14034 SE 201st St': 808, '15424 SE 9th St': 1060, '11224 SE 306th Pl': 276, '1605 S 245th Pl': 1147, '12425 415th Ave SE': 528, '3225 NE 92nd St': 2722, '3922 154th Ave SE': 3053, '3140 Franklin Ave E': 2654, '10212 NE 156th Pl': 71, '2021 NE 100th St': 1687, '27736 23rd Avenue South': 2419, '8436-8438 41st Ave SW': 4233, '1036 4th St': 106, '23525 SE 32nd Way': 2021, '3314 NW 75th St': 2793, '14104 119th Ave NE': 820, '20120 137th Ave NE': 1673, '7201-7399 55th Ave NE': 3921, '17052 4th Ave NE': 1295, '5172-5198 Heather Ave SE': 3507, '30822 36th Ct SW': 2619, '4801-4899 6th Ave NW': 3402, '23017 SE 281st Ct': 1954, '17825 4th Ave SW': 1399, '3628 59th Ave SW': 2936, '4460 332nd Ave SE': 3291, '2019 Aberdeen Pl SE': 1684, '121 NE 147th St': 440, '4458 51st Ave SW': 3290, '7542 21st Ave SW': 4020, '15804 198th Pl NE': 1101, '26069 SE 154th St': 2274, '4314 NE 6th Pl': 3227, '2640 NW 56th St': 2307, '15712 NE 136th Pl': 1091, '26429 SE 154th Pl': 2314, '3923 229th Pl SE': 3056, '6222 30th Ave NE': 3731, '32418 NE 50th St': 2733, '19334 89th Ave NE': 1604, '4071 156th Ave SE': 3114, '36850 204th Ave SE': 2960, '7425 Snowberry Ave SE': 3986, '3400 21st Ave W': 2820, '5944-6082 Delridge Way SW': 3666, '35229 SE Terrace St': 2894, '13800 453rd Ave SE': 774, '9927 174th Ave SE': 4502, '29734 215th Terrace SE': 2537, '5608 NE 5th Cir': 3615, '8053 29th Ave NW': 4135, '13256 242nd Pl SE': 685, '7528 N Fork Rd SE': 4012, '13134 234th Ct NE': 663, '13420 SE 182nd St': 719, '925 48th Ct': 4398, '151 Euclid Ave': 1007, '205-206 Euclid Ave': 1722, '22314 NE 11th Pl': 1895, '13615 NE 100th St': 752, '1411 N 48th St': 823, '120 31st Ave E': 402, '23140 NE 14th Ct': 1977, '12645 SE 27th St': 580, '3187 NE Larkspur Ln': 2682, '18915 SE 42nd Pl': 1533, '1765 267th Ct SE': 1382, '8624 Island Dr S': 4275, '24502 SE Mirrormont Dr': 2123, '14319 85th Pl NE': 882, '2120 NE 168th St': 1786, '209 30th Ave E': 1757, '10512 128th Ave NE': 132, '9126 45th Ave SW': 4359, '20220 8th Ave S': 1692, '11821 NE 48th Pl': 383, '13026 10th Ave NW': 644, '125 29th Ave': 542, '2171 Boyer Ave E': 1850, '3434 33rd Ave W': 2851, '5211 116th Pl SE': 3517, '3503 NE 44th St': 2880, '114 SW 292nd St': 301, '8536 Interlake Ave N': 4256, '3930 NE Belvoir Pl': 3058, '17132 SE 100th St': 1317, '10204 168th Pl NE': 66, '218 109th Ave SE': 1854, '12621 SE 300th Way': 571, '14013 Ashworth Ave N': 800, '34010 SE Sorenson St': 2823, '2506 166th Ave NE': 2180, '8814 218th Ave NE': 4294, '4515 SW Trenton St': 3309, '4924 SW 314th Pl': 3433, '4312 Woodlawn Ave N': 3224, '22912 SE 268th Pl': 1943, '27106 NE Miller St': 2363, '13129 195th Pl SE': 661, '1014 W Garfield St': 51, '14150 75th Ave NE': 835, '2601 21st Ave S': 2263, '12807 7th Ave S': 603, '4529 135th Ave SE': 3320, '1804 E Beaver Lake Dr SE': 1419, '1701 N 204th Pl': 1278, '8681 Beacon Ave S': 4281, '26408 NE 70th St': 2310, '17717 113th Pl SE': 1385, '8040 39th Ave NE': 4127, '901 N 97th St': 4328, '519 N 104th St': 3508, '14017 Roslyn Pl N': 803, '30001-30021 55th Pl S': 2547, '16026 SE 137th Terrace': 1138, '22721-22727 SE 27th St': 1928, '18027 SE 128th St': 1416, '20927-20999 2nd Ave S': 1760, '1857 41st Ave E': 1497, '353 NW 88th St': 2901, '18427 NE 26th Way': 1480, '2803 NE 62nd St': 2435, '13313 127th Pl NE': 696, '4532 185th Ave SE': 3328, '9288-9358 Holman Rd NW': 4402, '4509 185th Ave SE': 3304, '1318 29th Ave S': 669, '12001 173rd Pl NE': 406, '842 Summerhill Ridge Dr NW': 4227, '14359 19th Ave NE': 891, '935 4th Ave NE': 4421, '7809 12th Ave NE': 4078, '2027 Ferndale Ave NE': 1700, '792 Summerhill Ridge Dr NW': 4092, '1273 NE Hickory Ln': 598, '17122 NE 117th St': 1313, '10601 NE 138th Pl': 147, '412 NW 70th St': 3144, '11051 35th Ave NE': 233, '18114 NE 136th St': 1431, '25305 151st Pl SE': 2207, '6422 Marshall Ave SW': 3769, '310 NW 72nd St': 2628, '9712 4th Ave NW': 4469, '9020-9024 11th Ave NW': 4333, '1629 S 261st Pl': 1184, '2755 NW Pine Cone Dr': 2405, '2815 SW 107th St': 2449, '6009 52nd Ave NE': 3677, '3922 SW Henderson St': 3054, '5631 17th Ave SW': 3627, '14876 Juanita Woodinville Way NE': 961, '8652 17th Ave SW': 4279, '18305 Dayton Ave N': 1466, '1415 168th Ave NE': 833, '19007 80th Ave NE': 1541, '17435 SE 47th St': 1361, '23024-23198 17th Ave S': 1957, '32000-32072 NE 55th St': 2692, '17253 Ambaum Blvd S': 1341, '8409 NE 129th Pl': 4224, '25434 160th Ave SE': 2219, '18048 3rd Ave NW': 1420, '15007 75th Ave NE': 983, '5424 NE 10th St': 3572, '207 NW 5th St': 1744, '100 24th Ave E': 3, '11853 SE 176th Ct': 392, '12633 NE 133rd Pl': 577, '15607 SE 42nd Ct': 1076, '7422 NE 163rd St': 3984, '1708 NW 96th St': 1301, '33945 28th Pl SW': 2819, '16020 SE 2nd St': 1133, '24507 NE 77th Pl': 2125, '32827 22nd Ave SW': 2762, '415 NE 94th St': 3159, '2214 W Halladay St': 1887, '2560 39th Ave W': 2235, '12525 458th Ave SE': 554, '920 221st Ave NE': 4370, '9041 NE 160th Pl': 4344, '16022 SE 43rd St': 1136, '24201 SE 1st Pl': 2090, '13714 Ashworth Ave N': 764, '22344 NE 31st St': 1898, '5650 NE 55th St': 3633, '17649 NE 129th Pl': 1381, '3250 165th Ave SE': 2740, '21603 NE 29th St': 1837, '4711 University View Pl NE': 3377, '14707 SE 84th St': 934, '31607-31633 44th Ave S': 2668, '12116 SE 71st Pl': 449, '15418 216th Ave NE': 1058, '1703 NW 200th Ln': 1288, '3230 NE 95th St': 2727, '7434 Winona Ave N': 3990, '5215 32nd Ave S': 3520, '4206 SE Newport Way': 3178, '30020 43rd Pl S': 2553, '720 N 80th St': 3919, '8300 SE 82nd St': 4201, '31966 36th Ave SW': 2687, '2112 N 50th St': 1780, '2516 Yale Ave E': 2190, '1003 SW 307th St': 20, '135 25th Ave E': 727, '3665 Renton Ave S': 2955, '7000 23rd Ave NW': 3870, '710 S 23rd St': 3900, '8846 Midvale Ave N': 4306, '1435 104th Ave SE': 890, '16775 NE 86th Ct': 1254, '1749 NW 60th St': 1367, '105 SW 129th St': 127, '5628 NE 59th St': 3626, '1028 NE 153rd Ct': 86, '25823 NE 30th Ct': 2250, '25502 Kanasket Dr': 2225, '9626 NE 129th Pl': 4462, '21326 SE 277th Pl': 1798, '14613 6th Ave SW': 927, '19313 140th Pl SE': 1602, '2806 13th Ave W': 2438, '25339 SE 248th St': 2209, '8809 Densmore Ave N': 4293, '10627 NE 45th St': 157, '16635 SE 268th St': 1233, '19654 116th Ave SE': 1631, '5003 159th Ct NE': 3444, '4 128th Ave SE': 3068, '3845 Whitman Ave N': 3030, '32223 NE 88th St': 2720, '15204 88th Ave NE': 1023, '624 SW 137th St': 3735, '29645 10th Pl S': 2530, '1230 Warren Ave N': 499, '1713 22nd Ave S': 1316, '33331 NE Lake Joy Rd': 2805, '9703 130th Ave NE': 4468, '234 W Lake Sammamish Pkwy SE': 2005, '4140 53rd Ave SW': 3154, '206 Oakesdale Ave SW': 1732, '5531 Seward Park Ave S': 3598, '232 SW 154th St': 1983, '11105 126th Ave NE': 250, '18611 SE 307th Ln': 1503, '25525 SE 133rd St': 2230, '331 22nd Ave E': 2788, '4602 Woodlawn Ave N': 3345, '3723 S Chicago St': 2980, '12921 79th Pl NE': 621, '232nd Way': 1994, '6253-6299 15th Ave NE': 3739, '1718 N 175th St': 1327, '1225 N 41st Pl': 491, '12809-12907 206th Ave NE': 605, '9724 NE 14th St': 4476, '6708 14th Ave NW': 3821, '1902 45th Ave SW': 1548, '1234 22nd Ave E': 505, '32631 39th Ave SW': 2747, '4421-4564 186th Ave SE': 3270, '1200 N 27th Pl': 404, '4313 SW Willow St': 3226, '1761 17th Ave S': 1376, '3301-3389 289th Ave NE': 2776, '19501 135th Ave SE': 1615, '903 22nd Ave E': 4337, '3529 W Howe St': 2898, '20821 SE 135th St': 1751, '11907 SE 261st Pl': 395, '18227 SE 135th St': 1458, '5902 37th Ave SW': 3655, '138 Seattle Blvd S': 773, '15007-15299 37th Ave NE': 984, '18911 NE 165th Pl': 1531, '5146 S 303rd Pl': 3497, '3827 39th Ave S': 3022, '4703-4707 4th Ave NE': 3372, '1010 NW Inneswood Dr': 40, '517 32nd Ave S': 3505, '733 1st Ave N': 3960, '32016 8th Ave S': 2693, '27000-27080 201st Ave SE': 2351, '8514 S 124th St': 4243, '19302 65th Pl NE': 1597, '2145 Condon Way W': 1815, '605 N 178th St': 3692, '25408 Lake Wilderness Country Club Dr SE': 2215, '3235 30th Ave W': 2728, '13248 Occidental Ave S': 684, '11304 Corliss Ave N': 294, '11017 101st Pl NE': 220, '10908 101st Pl NE': 205, '3631 Greenwood Ave N': 2938, '31898 50th Pl S': 2683, '7956 46th Ave S': 4102, '12303 Sand Point Way NE': 500, '513 N 46th St': 3491, '2814 13th Ave W': 2448, '27930 NE 147th Pl': 2429, '7401 92nd Pl SE': 3976, '30633 21st Ave SW': 2613, '544 NE 84th St': 3577, '1825 251st Pl SE': 1460, '5200-5298 90th Ave SE': 3512, '3612 Interlake Ave N': 2924, '434 Pullman Ave': 3240, '1669 28th Ave NE': 1237, '235 Thelma St': 2018, '12207 NE 139th Pl': 468, '8448 Delridge Way SW': 4236, '624 Lake Washington Blvd E': 3734, '23733 NE Salal Pl': 2036, '24345 35th Pl S': 2114, '14816 SE 278th St': 954, '27469-27501 SE 154th Pl': 2396, '4022 SW Walker St': 3095, '28123 123rd Pl SE': 2445, '15020 SE 281st St': 994, '17622 12th Ave SW': 1380, '2509 33rd Ave S': 2183, '7304 217th Pl NE': 3944, '11921 SE 205th St': 398, '8230 Corliss Ave N': 4188, '12612 23rd Ave S': 568, '3002 109th Ave SE': 2550, '13711 SE 251 Pl': 762, '18748 SE 330th St': 1519, '1914 S 375th St': 1563, '14317 22nd Ave NE': 880, '468 Scenic Way': 3370, '4305 S Webster St': 3220, '1816 26th Ave': 1443, '1031 272nd Pl SE': 91, '5933 S Eastwood Dr': 3663, '13221 3rd Ave NW': 676, '5524 161st Pl NE': 3595, '3220 170th Ave NE': 2714, '806 15th Ave E': 4138, '2561 3rd Ave W': 2236, '13812 196th Ave NE': 778, '9842 Vineyard Crest': 4493, '1012 N 42nd Pl': 45, '8013 20th Ave NE': 4109, '13611 Bear Creek Rd NE': 750, '1237 S Sullivan St': 511, '12227 47th Ave S': 477, '17128 NE 92nd St': 1314, '365 Halladay St': 2948, '10621 NE 107th Pl': 153, '2121 46th Ave SW': 1787, '32817 10th Pl SW': 2759, '17109 139th Pl SE': 1307, '168 S 192nd Pl': 1255, '15451 22nd Ave SW': 1062, '8565 E Mercer Way': 4262, '9202A Interlake Ave N': 4373, '36521 SE 94th St': 2950, '15917 NE 109th Way': 1116, '322 9th Ave N': 2712, '4714 Thackeray Pl NE': 3379, '4924 SE 2nd Pl': 3432, '744 N 83rd St': 3994, '2973-3563 SW 172nd St': 2536, '4010 Linden Ave N': 3085, '1417 4th Ave W': 839, '2113 15th Ave S': 1781, '7630 Todd Pl': 4045, '743 N 71st St': 3988, '2050 14th Ave W': 1723, '19505 NE 143rd St': 1617, '14513-14521 164th Pl SE': 913, '2411 Meadow Ave N': 2073, '19490 SE 57th Pl': 1613, '7021 24th Ave NW': 3881, '31714 125th Pl SE': 2675, '15407 SE 252nd Pl': 1055, '29805-29821 129th Pl SW': 2540, '19707 NE 181st St': 1634, '3005 211th Ave NE': 2561, '33134 3rd Ct SW': 2792, '629-899 Cedar Ave S': 3744, '3809 260th Ave SE': 3002, '4205 NE 169th Ct': 3176, '12727 2nd Ave SW': 596, '2211 20th Ave S': 1880, 'East Lake Sammamish Trail': 4512, '10614 57th Ave S': 152, '4609-4699 Preston-Fall City Rd SE': 3347, '206-458 Lingering Pine Dr NW': 1734, '6255 4th Ave NW': 3740, '7418 Dogwood Ln SE': 3982, '14320 84th Ave NE': 884, '13532 15th Pl NE': 735, '17814 161st Ave SE': 1395, '9507 Ashworth Ave N': 4444, '13615 Somerset Ln SE': 753, '3331 S 368th Pl': 2802, '32704 33rd Ave SW': 2752, '13905 184th Ave NE': 785, '4127 Fauntleroy Way SW': 3147, '429 Milwaukee Blvd S': 3214, '23801 SE 162nd St': 2040, '15217 80th Ave NE': 1027, '401 31st Ave E': 3082, '1614 32nd Ave': 1157, '3319 S 262nd St': 2794, '18616 215th Way NE': 1504, '21423 114th Pl SE': 1813, '9828 159th Pl NE': 4492, '2655 166th Ave SE': 2331, '9921 227th Way NE': 4501, '3026 S Star Lake Rd': 2583, '3502 Morris Ave S': 2878, '1211 NE 135th St': 444, '400-498 211th Pl NE': 3072, '439 SW 156th St': 3252, '18730-18798 109 Ln SE': 1517, '16828 166th Pl SE': 1262, '7701 16th Ave NW': 4054, '21612 SE 290th Ct': 1840, '445 Meadow Dr SE': 3289, '11110 NE 38th Pl': 253, '26621 SE 22nd Way': 2334, '2084-2104 144th Ave SE': 1754, '21630-21648 NE 67th St': 1843, '29606 SE 286 St': 2525, '31701-31799 SE 291st St': 2673, '819 NE 125th St': 4168, '29612 2nd Ave SW': 2527, '33030 NE 201st St': 2781, '21227 SE 278th Way': 1790, '108-150 Union Ave SE': 186, '8608 N Mercer Way': 4270, '9610 8th Ave NE': 4457, '15610 NE 159th St': 1077, '1721 NE 98th St': 1333, '11131 SE 183rd Pl': 257, '2653 46th Ave SW': 2328, '19226 76th Pl NE': 1585, '10312 Linden Ave N': 92, '9245-9249 Fremont Ave N': 4395, '33001 NE 24th St': 2774, '7070 270th Pl SE': 3895, '820 NW 95th St': 4171, '10834 31st Ave SW': 195, 'Cedar to Green River Trail': 4511, '6521 Fremont Ave N': 3795, '9908 S 210th Pl': 4500, '5940 California Ave SW': 3665, '906 17th Ave': 4349, '5411 Fauntleroy Way SW': 3565, '25005 NE Patterson Way': 2168, '3503 NE 43rd St': 2879, '2500 Mulberry Walk NE': 2165, '9155 NE 21st Pl': 4364, '106 24th Ave E': 145, '17050 14th Avenue Northeast': 1292, '9413 34th Ave SW': 4431, '3603 W Mercer Way': 2918, '19211 SE 342nd St': 1577, '3709 131st Ave NE': 2967, '3017 SW Hinds St': 2577, '1216 86th Ave NE': 459, '4436-4446 W Mercer Way': 3280, '31907 NE 139th St': 2686, '4430 Letitia Ave S': 3276, '16512 SE 64th Pl': 1217, '9214 Cyrus Ave NW': 4378, '2346 N 59th St': 2016, '5537 S 119th St': 3600, '21709 SE 255th Pl': 1849, '7953 14th Ave SW': 4101, '5220 SW Pritchard St': 3522, '16411 120th Ave SE': 1201, '215 243rd Ave SE': 1822, '20325 NE 198th St': 1708, '2420 Dogwood St SE': 2088, '17217 Woodside Dr SE': 1335, '5145 S Roxbury St': 3496, '11725 NE 102nd Pl': 367, '1614 33rd Ave': 1158, '1733 NE 88th St': 1351, '11461-11577 172nd Ave NE': 318, '1047-1099 S 130th St': 124, '11618 NE 65th St': 344, '8223 SE 71st St': 4187, '9202 SE 46th St': 4372, '26405 218th Ave SE': 2309, '5900 20th Ave NW': 3653, '30928 148th Ave SE': 2626, '23549 NE 111th St': 2023, '4410 Burke Ave N': 3261, '20248 20th Ave NE': 1697, '24127 SE 45th Pl': 2077, '570 Wilderness Peak Dr NW': 3635, '11521 22nd Ave NE': 332, '414 14th Ave': 3153, '13222 NE 193rd Pl': 678, 'Indian Trail': 4515, '29621 18th Ave S': 2529, '9319 45th Ave SW': 4410, '8107 165th Ave NE': 4149, '124 SW 185th St': 517, '124 NE 61st St': 515, '731 McGilvra Blvd E': 3946, '9640 NE 32nd St': 4464, '2455 Queen Anne Ave N': 2126, '13730 2nd Ave NW': 768, '9311 NE 142nd St': 4406, '19693-19799 SE Maple Valley Hwy': 1633, '16580 SE 57th Pl': 1225, '16251 12th Ave SW': 1181, '618 NW 49th St': 3717, '950 NW 60th St': 4443, '8434 W Mercer Way': 4232, '23014 Vashon Hwy SW': 1953, '3219 34th Ave W': 2709, '10442 SE 13th St': 122, '5650 Fauntleroy Way SW': 3632, '1716 California Ave SW': 1323, '7815 Stroud Ave N': 4082, '10774 155th Pl NE': 183, '22442-22446 Southeast 281st Court': 1904, '1313 4th St': 662, '18416 172nd Ct SE': 1478, '8082-8160 142nd Ave NE': 4143, '512-598 21st Ave': 3486, '2476 239th Pl NE': 2143, '18125 194th Ave NE': 1437, '2065 NE Nelson Ln': 1740, '15801 63rd Ave NE': 1098, '2831 SW 327th St': 2469, '23726 NE 134th Pl': 2035, '19293 Stone Ave N': 1594, '4018 NE 6th Ct': 3089, '25523 123rd Pl SE': 2229, '7349 24th Ave NW': 3969, '18913 SE 63rd Pl': 1532, '2448 137th Ave SE': 2122, '1020 163rd Ave SE': 62, '8028 27th Ave NE': 4123, '7408 138th Pl NE': 3979, '10412 Aqua Way S': 113, '4958 12th Ave S': 3439, '9045 NE 40th Pl': 4345, '1405 E Maple St': 812, '27020 NE Ring St': 2354, '420 Boylston Ave E': 3171, '36400-36452 51st Ave S': 2941, '1600-1608 25th Ave': 1124, '18307 NE 19th Pl': 1467, '16700 SE 161st St': 1238, '5461 S Othello St': 3583, '171 Lake Washington Blvd': 1304, '4812 S Chicago St': 3411, '718 N 95th St': 3914, '1673 Rosemont Blvd': 1253, '14700 Burke Ave N': 933, '27747 SE 24th Way': 2420, '10711 SW 111th Pl': 171, '19615 182nd Ave NE': 1627, '4437 55th Ave NE': 3282, '7325 Earl Ave NW': 3955, '4030-4198 S 186th St': 3099, '12446 21st Ave S': 533, '12033 NE 136th Pl': 420, '13540 Burke Ave N': 736, '4115 SW 106th St': 3137, '14710 122nd Pl NE': 936, '3883 112th Ave NE': 3036, '11409 SE 71st Pl': 309, '4902 159th Pl SE': 3426, '8421 SE 72nd Pl': 4229, '18015 25th Ave NE': 1414, '324 NW 48th St': 2731, '2830 177th Ave NE': 2467, '6101-6149 Corliss Ave N': 3700, '1707-1713 3rd Ave N': 1299, '2301 California Ave SW': 1950, '17081-17183 SE Wax Rd': 1302, '2711 126th Ave SE': 2364, '15018 NE 10th Pl': 992, '16541 NE 27th Pl': 1223, '8126-8196 Forest Ave SE': 4157, '16014 16th Ave SW': 1128, '217 SW 191st St': 1847, '2278 72nd Ave SE': 1933, '6206 Phinney Ave N': 3722, '16722 32nd Pl NE': 1246, '4118 32nd Ave SW': 3142, '4222 S 288th Pl': 3187, '9250 SE 36th Pl': 4399, '29140 42nd Ave S': 2505, '15846 196th Pl NE': 1110, '14405 274th Ct NE': 897, '7741 22nd Ave NE': 4070, '3616 NE 65th St': 2928, '7125 Silent Creek Ave SE': 3905, '7617 NE 201st Pl': 4042, '12467 NE 171st Pl': 538, '213 26th Ave E': 1794, '9314 Ash Ave SE': 4408, '7921 45th Ave SW': 4094, '615 NW 92nd St': 3715, '5138 NE 8th St': 3494, '6544 18th Ave SW': 3805, '10037 Interlake Ave N': 22, '353 N 105th St': 2900, '7730 33rd Ave NW': 4065, '3446 77th Ave SE': 2858, '3810 145th Ave SE': 3005, '1109 32nd Ave': 243, '7558 32nd Ave NW': 4032, '921 S 223rd St': 4375, '28511 10th Ave S': 2481, '14319 165th Pl SE': 881, '721 222nd Pl NE': 3926, '404 SW 197th St': 3105, '475-547 Monroe Ave NE': 3391, '26205 119th Dr SE': 2290, '200 Pike St SE': 1649, '11549 SE 319th Pl': 337, '4607 SW Cloverdale St': 3346, '6000-6048 22nd Ave S': 3671, '4254 33rd Ave W': 3205, '8622 NE 139th St': 4274, '2901 W Elmore St': 2498, '18527 Kenlake Pl NE': 1492, '6917 28th Ave NW': 3864, '316 Lake Washington Blvd S': 2663, '21560 SE 275th Ct': 1831, '2145 N 88th St': 1817, '13547 SE 83rd St': 739, '2363 30th Ave NE': 2033, '15905 Saybrook Dr NE': 1114, '322 16th Ave': 2711, '11909 SE 228th Pl': 396, '14836 Densmore Ave N': 958, '7557 35th Ave NE': 4030, '16501-16515 Carlyle Hall Rd N': 1216, '8715 17th Ave NW': 4283, '1522 55th Ct SE': 1028, '1807 17th Ave S': 1426, '5242 336th Ave SE': 3528, '27204 116th Pl SE': 2377, '1456 NW 185th St': 920, '33610 51st Ave S': 2812, '920 163rd Ave SE': 4369, '1400 S 359th St': 788, '14800-14822 88th Ave NE': 947, '30004 SE Lake Retreat S Dr': 2549, '14937 57th Ave S': 971, '14923 280th Pl NE': 967, '3305 39th Ave W': 2783, '14235 160th Ave NE': 863, '2000 NE 113th St': 1652, '2033 211th Pl SE': 1709, '14244 140th Ave SE': 865, '11400-11598 SE 114th Pl': 302, '504 Shelton Ct NE': 3462, '26021 NE 25th St': 2269, '1909 N 195th St': 1556, '3755 S 168th St': 2991, '16824 11th Pl NE': 1261, '10872 SE 318th Pl': 201, '13622 NE 136th Pl': 756, '3047 21st Ave W': 2602, '16 R Pl NE': 1123, '6520-6588 8th Ave NW': 3794, '6133 147th Pl NE': 3709, '24217 181st Pl SE': 2093, '10441 SE 24th Pl': 121, '2559 NE 98th St': 2234, '15924 NE 53rd St': 1119, '26054 SE 23rd Pl': 2273, '5491 175th Pl SE': 3589, '4620 Kennedy Ave SE': 3355, '12901 NE 136th St': 617, '36023 3rd Ave S': 2917, '7590 86th Ave SE': 4034, '4036 S 119th St': 3102, '808 Hoquiam Ave NE': 4141, '1458-1462 29th Pl NE': 922, '4531 205th Pl NE': 3323, '833 SW 361st St': 4214, '24231 NE 5th Pl': 2098, '12902 SE 158th Pl': 618, '12713 SE 302nd St': 590, '16231 NE 29th St': 1176, '12208 20th Ave S': 469, '21023-21029 NE 42nd St': 1766, '12145 SE 260th Pl': 456, '1001 Whitman Ct NE': 10, '4137 48th Ave SW': 3152, '19415 107th Ave SE': 1609, '1422 S 282nd Pl': 858, '3539 NW 67th St': 2906, '29611 21st Ave S': 2526, '11515 4th Ave NE': 327, '5212 Wallingford Ave N': 3518, '18218 Evanston Ave N': 1455, '14013 101st Pl NE': 799, '4446 S 160th St': 3288, '4531 S Lucile St': 3325, '5419 156th Ave NE': 3567, '1323 145th Ave SE': 680, '8121 NE 147th Pl': 4155, '17013 NE 133rd St': 1281, '11401 SE 219th Pl': 304, '15839 84th Ave NE': 1108, '3311 SE 17th St': 2790, '4216 232nd Ave NE': 3182, '13219 424th Ave SE': 674, '5038 48th Ave NE': 3460, '1106 25th Ave E': 236, '2548 111th Ave SE': 2222, '309 N 46th St': 2622, '26118 SE 39th Ct': 2280, '29031 40th Ave S': 2500, '24038 SE 13th Pl': 2065, '392 Wilderness Peak Dr NW': 3050, '2145 N 178th St': 1816, '11738 1st Ave NE': 370, '26516 235th Ave SE': 2323, '7822 NE 14th St': 4085

In [6]:
df.drop(columns=["date","street","city","statezip","country"],inplace=True)

In [7]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,encoded_street,encoded_city,encoded_zip,encoded_country
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,1522,36,62,0
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,3899,35,58,0
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,2291,18,26,0
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,4263,3,7,0
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,4352,31,31,0

In [8]:
#feature selection:
x = df.drop(columns=["price"])
y = df["price"]

In [9]:
#data splitting
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [13]:
#model selection 
model = LinearRegression()
tree = DecisionTreeRegressor(max_depth=7,random_state=42)
random = RandomForestRegressor(n_estimators=100,max_depth=7,random_state=42)

In [16]:
#model training using linear regression:
model.fit(x_train,y_train)

LinearRegression()

In [17]:
#model training using desicion tree regression
tree.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=7, random_state=42)

In [18]:
#model training using random forest regression
random.fit(x_train,y_train)

RandomForestRegressor(max_depth=7, random_state=42)

In [19]:
y_pred = model.predict(x_test)
r2_score(y_test,y_pred)

0.0329025386835301

In [20]:
y_pred = tree.predict(x_test)
r2_score(y_test,y_pred)

0.022221539430320125

In [21]:
y_pred = random.predict(x_test)
r2_score(y_test,y_pred)

0.04237470132524179