In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,LabelEncoder
from sklearn.metrics import r2_score

In [4]:
df = pd.read_csv(r"C:\Users\Anushkha Bhagra\Downloads\ML\laptop_data_cleaned.csv")
df.head()

,Company,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
0,Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
1,Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
2,HP,Notebook,8,1.86,10.329931,0,0,141.211998,Intel Core i5,0,256,Intel,Others
3,Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
4,Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac

In [5]:
df.isnull().sum()

Company        0
TypeName       0
Ram            0
Weight         0
Price          0
TouchScreen    0
Ips            0
Ppi            0
Cpu_brand      0
HDD            0
SSD            0
Gpu_brand      0
Os             0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(1)

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
# encoding the categorical data :
label = LabelEncoder()
df["encoded_company"] = label.fit_transform(df["Company"])
var1 = dict(zip(df["encoded_company"],df["Company"]))
print(var1)

df["encoded_typename"] = label.fit_transform(df["TypeName"])
var2 = dict(zip(df["TypeName"],df["encoded_typename"]))
print(var2)

df["encoded_cpu"] = label.fit_transform(df["Cpu_brand"])
var3 = dict(zip(df["Cpu_brand"],df["encoded_cpu"]))
print(var3)

df["encoded_Gpu"] = label.fit_transform(df["Gpu_brand"])
var4 = dict(zip(df["Gpu_brand"],df["encoded_Gpu"]))
print(var4)

df["encoded_os"] = label.fit_transform(df["Os"])
var5 = dict(zip(df["Os"],df["encoded_os"]))
print(var5)

{1: 'Apple', 7: 'HP', 0: 'Acer', 2: 'Asus', 4: 'Dell', 10: 'Lenovo', 3: 'Chuwi', 11: 'MSI', 13: 'Microsoft', 16: 'Toshiba', 8: 'Huawei', 18: 'Xiaomi', 17: 'Vero', 14: 'Razer', 12: 'Mediacom', 15: 'Samsung', 6: 'Google', 5: 'Fujitsu', 9: 'LG'}
{'Ultrabook': 4, 'Notebook': 3, 'Netbook': 2, 'Gaming': 1, '2 in 1 Convertible': 0, 'Workstation': 5}
{'Intel Core i5': 2, 'Intel Core i7': 3, 'AMD Processor': 0, 'Intel Core i3': 1, 'Other Intel Processor': 4}
{'Intel': 1, 'AMD': 0, 'Nvidia': 2}
{'Mac': 0, 'Others': 1, 'Windows': 2}

In [9]:
# droping the categorical columns:
df.drop(columns=["Company","TypeName","Cpu_brand","Gpu_brand","Os"],inplace=True)
df.head()

,Ram,Weight,Price,TouchScreen,Ips,Ppi,HDD,SSD,encoded_company,encoded_typename,encoded_cpu,encoded_Gpu,encoded_os
0,8,1.37,11.175755,0,1,226.983005,0,128,1,4,2,1,0
1,8,1.34,10.776777,0,0,127.677940,0,0,1,4,2,1,0
2,8,1.86,10.329931,0,0,141.211998,0,256,7,3,2,1,1
3,16,1.83,11.814476,0,1,220.534624,0,512,1,4,3,0,0
4,8,1.37,11.473101,0,1,226.983005,0,256,1,4,2,1,0

In [10]:
#feature selection:
x = df[["Ram","Weight","TouchScreen","Ips","Ppi","HDD","SSD","encoded_company","encoded_typename","encoded_cpu","encoded_Gpu","encoded_os"]]
y = df["Price"]

In [11]:
#splitting the data:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state =42)

In [12]:
#model selection:
model = LinearRegression()

#model training:
model.fit(x_train,y_train)

LinearRegression()

In [13]:
#model testing:
y_pred = model.predict(x_test)
y_pred

array([10.88590628, 10.28002844, 11.43531126, 10.8697488 , 10.10873418,
       10.4938454 , 10.83102302, 11.2069277 , 10.58138891, 10.85368149,
       10.88950683, 10.93478591, 10.1561213 , 11.15797189, 10.77167723,
       11.15715936, 11.26684038, 10.48294101, 10.47496211, 11.41055377,
       11.55421896, 10.38641965, 10.23952483, 10.41608097, 10.76216742,
       10.91074981, 10.68820276, 10.46354098, 12.22635813, 10.87869101,
       10.61882384, 10.70147492, 10.56382904, 10.3718806 , 10.45255332,
       11.5430262 , 11.45241063, 10.00206063, 10.50617963, 10.59544092,
       10.30854665, 11.00783145, 11.06229486, 10.75276074, 10.51257484,
       10.25799268, 10.25694483, 11.40495783, 10.55503009, 10.4425562 ,
       11.04034227, 10.56315381, 10.66790219, 10.62050718, 11.04633376,
       10.61436639, 10.67853698, 10.0489449 , 11.01841113, 10.51323291,
       11.02531759, 10.09012238, 11.28133986, 10.41723576, 10.28167831,
       10.79433257, 11.03320311, 12.27299553, 10.57077616, 10.9426348 ,
       10.74605576, 10.56101963, 11.27834966, 11.315188  , 10.53414709,
       10.68799124, 10.17345508, 10.46086879, 10.95094068, 10.37753718,
       10.91991206, 10.81816833, 11.10346607, 10.67248245, 11.3180419 ,
       10.30671913, 10.94472868, 12.03732642, 10.43778116, 11.83746758,
       11.09494649, 10.32309042, 10.83777089, 10.86429554, 10.1192958 ,
       11.1020213 , 10.51449261, 11.1234705 , 12.26464883, 10.38797611,
       11.26571067, 11.22144163, 10.51172035, 10.56221815, 10.93573728,
       10.74544129, 10.24582268, 11.06293423, 10.84760223, 11.57167127,
       10.82330058, 10.76903546, 10.07416594, 11.05527172, 10.892835  ,
       11.45978208, 10.93148617, 11.11449213, 10.83363825, 10.81559617,
       11.24198104, 10.85441003, 10.80364345, 10.95294611, 10.6940432 ,
       10.81679551, 10.29124756, 11.4618242 , 10.66939703, 10.85425446,
       10.89677448, 10.6117193 , 10.42288032, 10.64631359, 10.42934118,
       10.85835886, 10.49323238, 10.14207029, 10.58190075, 11.10398113,
       10.40941315, 10.84482272, 10.46584361, 10.22681846, 11.40786411,
       11.61569959, 10.88590628, 10.56431374, 11.37964265, 11.76266023,
       10.81324626, 10.46333704, 11.26845044, 10.97618473, 10.66724224,
       10.96559529, 11.06288996, 10.3322822 , 10.28952956, 10.32699782,
       11.16768791, 10.55475013, 10.97898327, 13.19815702, 11.26373082,
       10.54753753, 11.18024022, 11.07158985, 10.4604727 , 10.59973361,
       10.81928533, 11.13501573, 10.87808785, 10.68985928, 11.30622761,
       10.71950402, 10.80591907, 10.84415493, 11.09137381, 10.60870577,
       10.57577596, 10.91840217, 10.58264579, 11.01741916, 10.60732374,
       10.94487284, 11.1386702 , 10.6137265 , 10.25851451, 10.62967445,
       10.95495696, 10.33382456, 10.20045989, 10.39076521, 10.08172786,
       10.15646096, 10.74843861, 10.89742621, 10.80961507, 10.72510622,
       11.04461952, 10.73284934, 10.77476275, 10.14193392, 10.3458772 ,
       11.45021979, 10.24665588, 10.47839122, 10.67297717, 11.27890093,
       10.37092881, 11.24247205, 10.4623454 , 10.86763495, 10.88159749,
       10.47717128, 10.87044165, 10.48723067, 11.68762234, 10.99427225,
       10.64019759, 10.85695369, 11.41531713, 10.86763495, 10.35133574,
       10.5365756 , 10.55900072, 10.63437217, 11.8225963 , 10.17345508,
       10.67298358, 10.64653222, 10.50403159, 10.92462923, 10.9532505 ,
       11.12525992, 10.63218413, 10.98775167, 10.6241232 , 11.59191597,
       10.31553404, 10.61216416, 10.30201753, 10.32458913, 11.01741916,
       10.64087403, 10.27579174, 11.0282719 , 10.3484148 , 10.85425446,
       11.43755359, 10.82483545, 14.41766098, 10.87798624, 10.90862419])

In [14]:
# model accuracy:
r2_score(y_test,y_pred)

0.553666209928575

In [16]:
#model prediction:
#Ram	Weight	Price 	TouchScreen	Ips	Ppi	HDD	SSD	encoded_company	encoded_typename	encoded_cpu	encoded_Gpu	encoded_os
Ram = int(input("enter the ram:"))
Weight = float(input("enter the weight:"))
TouchScreen = int(input('enter the value of touch screen:'))
Ips = int(input('enter the value of Ips:'))
Ppi =int(input("enter the value of Ppi:"))
HDD = int(input("enter the value of HDD:"))
SSD = int(input("enter the value of SSD:"))
company = int(input("enter the nmae of the comapany:-->{1: 'Apple', 7: 'HP', 0: 'Acer', 2: 'Asus', 4: 'Dell', 10: 'Lenovo', 3: 'Chuwi', 11: 'MSI', 13: 'Microsoft', 16: 'Toshiba', 8: 'Huawei', 18: 'Xiaomi', 17: 'Vero', 14: 'Razer', 12: 'Mediacom', 15: 'Samsung', 6: 'Google', 5: 'Fujitsu', 9: 'LG'}"))
type_name = int(input("enter the type name:--> {'Ultrabook': 4, 'Notebook': 3, 'Netbook': 2, 'Gaming': 1, '2 in 1 Convertible': 0, 'Workstation': 5}"))
cpu = int(input("enter the value of the cpu--> {'Intel Core i5': 2, 'Intel Core i7': 3, 'AMD Processor': 0, 'Intel Core i3': 1, 'Other Intel Processor': 4}"))
gpu = int(input("enter the value of the gpu--> {'Intel': 1, 'AMD': 0, 'Nvidia': 2}"))
os = int(input("enter the value of the Os:--> {'Mac': 0, 'Others': 1, 'Windows': 2}"))
pred = model.predict([[Ram,Weight,TouchScreen,Ips,Ppi	,HDD,SSD,company,type_name,cpu,gpu,os]])
print("selling price of the laptop is:",pred)

enter the ram: 8
enter the weight: 1.34
enter the value of touch screen: 0
enter the value of Ips: 1
enter the value of Ppi: 229
enter the value of HDD: 0
enter the value of SSD: 1
enter the nmae of the comapany:-->{1: 'Apple', 7: 'HP', 0: 'Acer', 2: 'Asus', 4: 'Dell', 10: 'Lenovo', 3: 'Chuwi', 11: 'MSI', 13: 'Microsoft', 16: 'Toshiba', 8: 'Huawei', 18: 'Xiaomi', 17: 'Vero', 14: 'Razer', 12: 'Mediacom', 15: 'Samsung', 6: 'Google', 5: 'Fujitsu', 9: 'LG'} 1
enter the type name:--> {'Ultrabook': 4, 'Notebook': 3, 'Netbook': 2, 'Gaming': 1, '2 in 1 Convertible': 0, 'Workstation': 5} 2
enter the value of the cpu--> {'Intel Core i5': 2, 'Intel Core i7': 3, 'AMD Processor': 0, 'Intel Core i3': 1, 'Other Intel Processor': 4} 3
enter the value of the gpu--> {'Intel': 1, 'AMD': 0, 'Nvidia': 2} 2
enter the value of the Os:--> {'Mac': 0, 'Others': 1, 'Windows': 2} 2

selling price of the laptop is: [11.01384848]

E:\anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(