In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

In [19]:
df = pd.read_csv(r"C:\Users\Anushkha Bhagra\Downloads\ML\ensemble_learning\archive (1)\NFLX.csv")
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-02-05,262.000000,267.899994,250.029999,254.259995,254.259995,11896100
1,2018-02-06,247.699997,266.700012,245.000000,265.720001,265.720001,12595800
2,2018-02-07,266.579987,272.450012,264.329987,264.559998,264.559998,8981500
3,2018-02-08,267.079987,267.619995,250.000000,250.100006,250.100006,9306700
4,2018-02-09,253.850006,255.800003,236.110001,249.470001,249.470001,16906900

In [3]:
df.drop(columns=["Adj Close","Date"],inplace=True)

In [16]:
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-02-05,262.000000,267.899994,250.029999,254.259995,254.259995,11896100
1,2018-02-06,247.699997,266.700012,245.000000,265.720001,265.720001,12595800
2,2018-02-07,266.579987,272.450012,264.329987,264.559998,264.559998,8981500
3,2018-02-08,267.079987,267.619995,250.000000,250.100006,250.100006,9306700
4,2018-02-09,253.850006,255.800003,236.110001,249.470001,249.470001,16906900
...,...,...,...,...,...,...,...
1004,2022-01-31,401.970001,427.700012,398.200012,427.140015,427.140015,20047500
1005,2022-02-01,432.959991,458.480011,425.540009,457.130005,457.130005,22542300
1006,2022-02-02,448.250000,451.980011,426.480011,429.480011,429.480011,14346000
1007,2022-02-03,421.440002,429.260010,404.279999,405.600006,405.600006,9905200
1008,2022-02-04,407.309998,412.769989,396.640015,410.170013,410.170013,7782400

In [4]:
df.isnull().sum()

Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
#feature selection:
x = df.drop(columns=["Close"])
y = df["Close"]

In [7]:
#data selection:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
#scaling:
scaler = StandardScaler()
x_train_scalar = scaler.fit_transform(x_train)
x_test_scaler = scaler.transform(x_test)

In [9]:
para_grid = {"max_depth": [3,5,6,7,9,11],
            "n_estimators": [100,150,200,250,300]}

In [21]:
tuning_model = RandomForestRegressor(random_state=42)

random_model = RandomizedSearchCV(param_distributions = para_grid,
                                 estimator = tuning_model,
                                 n_jobs= -1,
                                 cv =5,
                                 n_iter = 30,
                                 scoring= "r2",
                                 verbose=1)
random_model.fit(x_train_scalar,y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'max_depth': [3, 5, 6, 7, 9, 11],
                                        'n_estimators': [100, 150, 200, 250,
                                                         300]},
                   scoring='r2', verbose=1)

In [24]:
y_pred = random_model.predict(x_test_scaler)
r2_score(y_test,y_pred)

0.9977080885528291

In [25]:
y_pred_train = random_model.predict(x_train_scalar)
r2_score(y_train,y_pred_train)

0.9996099534906489

In [22]:
#predictive model:

In [31]:
#Open	High	Low		Volume
Open = int(input("enter your values"))
high = int(input("enter your values"))
low = int(input("enter your values"))
volume = int(input("enter your values"))
data = [[Open,high,low,volume]]
predict = scaler.transform(data)
print(f"at what value the stock will close:",predict)

enter your values 435
enter your values 567
enter your values 355
enter your values 573

at what value the stock will close: [[ 0.13986295  1.28919212 -0.53930838 -1.35731816]]

E:\anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(